name: dartsicord
description: A Discord library for Dart
version: 0.0.3
homepage: https://github.com/voximity/dartsicord

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: "^0.11.3+16"

dev_dependencies:
  test: ^0.12.0
